name: Build Pulumi

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  call-pulumi-workflow:
    uses: ../../aws/python/gh-app-preview-test/.github/workflows/pulumi.yaml
    with:
      stack-name: dev
    secrets:
      pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}