name: Build Pulumi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-pulumi-workflow:
    uses: notjosse/pulumi-home/.github/workflows/pulumi.yaml@main
    with:
      stack-name: dev
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  call-automation-api-workflow:
    uses: notjosse/pulumi-home/.github/workflows/automation-api-pulumi.yaml@main
    with:
      stack-name: dev
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}