name: Build Pulumi Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-pulumi-workflow:
    uses: notjosse/pulumi-home/.github/workflows/pulumi.yaml@main
    with:
      stack-name: dev
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # call-automation-api-workflow:
  #   uses: notjosse/pulumi-home/.github/workflows/automation-api-pulumi.yaml@main
  #   with:
  #     stack-name: dev
  #   secrets:
  #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}