name: Reusable Pulumi Workflow

on:
  workflow_call:
    inputs:
      stack-name:
        description: 'The name of the stack to operate on'
        required: true
        type: string
    secrets:
      pulumi-access-token:
        description: 'The Pulumi access token to use'
        required: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup python 3.11.6
      with:
        python-version: "3.11.6"
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: pulumi preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi-access-token }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: true