name: Pulumi Preview
on:
  workflow_call:
    inputs:
      stack-name:
        description: 'The name of the stack to operate on'
        required: true
        type: string
    secrets:
      PULUMI_ACCESS_TOKEN:
        description: 'The Pulumi access token to use'
        required: true
      aws-access-key-id:
        description: 'AWS Credentials access key id'
        required: true
      aws-region:
        description: 'AWS SSO region'
        required: true
      aws-secret-access-key:
        description: 'AWS Credentials secret access key'
        required: true
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-region: ${{ secrets.aws-region }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
      - name: Setup python env
        run: |
          echo "python3 venv setup"
          python3 -m venv venv
          echo "python3 source activate"
          source venv/bin/activate
          echo "python pip3 install"
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
        working-directory: ./aws/python/gh-app-preview-test
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: josse-pulumi-corp/gh-app-preview-test/dev
          comment-on-pr: true
          work-dir: ./aws/python/gh-app-preview-test
          # github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}