name: Pulumi Preview

on:
  workflow_call:
    inputs:
      stack-name:
        description: 'The name of the stack to operate on'
        required: true
        type: string
    secrets:
      pulumi-access-token:
        description: 'The Pulumi access token to use'
        required: true

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"
      - name: Setup python env
        run: |
          echo "python3 venv setup"
          python3 -m venv venv
          echo "python3 source activate"
          source venv/bin/activate
          echo "python pip3 install"
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
        working-directory: ./aws/python/gh-app-preview-test
      - uses: pulumi/actions@v3
        with:
          # command: preview
          stack-name: josse-pulumi-corp/gh-app-preview-test/dev
          comment-on-pr: true
          # github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: inherit
      - name: Pulumi Preview
        run: |
          pulumi preview
        working-directory: ./aws/python/gh-app-preview-test